name=roo_prefs
version=1.4.0
author=Dejwk <dejwk.oss@gmail.com>
maintainer=Dejwk <dejwk.oss@gmail.com>
sentence=Utility library for persistent settings using ESP32 NVS or Arduino Preferences, with namespaces and transactions.
paragraph=Useful in libraries, to store persistent settings (passwords, configuration) in an organized way.
category=Other
url=https://github.com/dejwk/roo_prefs
architectures=*
depends=roo_backport,roo_logging,roo_scheduler
